version: '2.3'
services:
  xl-deploy:
    build: xl-deploy
    ports:
    - 4516:4516
    environment:
    - ADMIN_PASSWORD=admin

  xl-release:
    build: xl-release
    ports:
    - 5516:5516
    depends_on:
    - xl-deploy
    environment:
    - ADMIN_PASSWORD=admin

  xl-cli:
    build: xl-cli
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "--xl-deploy-url", "http://xl-deploy:4516/", "--xl-release-url", "http://xl-release:5516/", "-f", "/data/configure-xl-devops-platform.yaml"]
    volumes:
    - ./data/:/data:ro

  jenkins:
    build: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - GITHUB_USER=psimon-XL
      - GITHUB_TOKEN=da028363e4dd3048b6fd059f58a6e832acaee5af
      - DOCKER_USER=psimon@xebialabs.com
      #- DOCKER_PASS=Demerit$1
    ports:
      - 8080:8080
      - 55888:55888