apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notification-mongodb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-mongodb
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: mongodb
        image: mongo:3.6.3
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db/
---
# Headless service for DNS record
apiVersion: v1
kind: Service
metadata:
  name: notification-mongodb
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None        
  selector:
    app: notification-mongodb
  ports:
  - port: 27017
